# Generated by Django 6.0.1 on 2026-01-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="condominium_fees",
            field=models.FloatField(default=None, null=True),
        ),
    ]
