# Generated by Django 6.0.1 on 2026-01-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0002_alter_advertisement_condominium_fees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="bienici_id",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="condominium_fees",
            field=models.FloatField(default=None),
        ),
    ]
