# Generated by Django 6.0.1 on 2026-01-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0003_alter_advertisement_bienici_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="condominium_fees",
            field=models.FloatField(default=None, null=True),
        ),
    ]
